# Generated by Django 5.1.3 on 2024-12-06 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='index',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='words',
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_no',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(blank=True, max_length=255, null=True)),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_translation', models.CharField(max_length=255)),
                ('correct_prompts', models.JSONField()),
                ('words_indices', models.JSONField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='backendDB.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng', models.CharField(max_length=255)),
                ('span', models.CharField(max_length=255)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='backendDB.lesson')),
            ],
        ),
    ]
