# Generated by Django 5.1.3 on 2024-12-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendDB', '0002_alter_lesson_options_remove_lesson_cards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='yearJoined',
            field=models.IntegerField(default=2024),
        ),
    ]
