# Generated by Django 5.1.3 on 2024-12-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendDB', '0003_alter_user_yearjoined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='correct_translation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
