# Generated by Django 5.1.3 on 2024-12-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendDB', '0004_alter_card_correct_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=250),
        ),
    ]
