# Generated by Django 5.1.3 on 2024-12-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendDB', '0005_alter_course_id_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
