# Generated by Django 5.1.3 on 2024-12-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendDB', '0006_alter_user_email_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='note',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
