# Generated by Django 5.1.3 on 2024-12-21 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendDB', '0007_card_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='times_missed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='asl',
            field=models.FileField(null=True, upload_to='media/'),
        ),
        migrations.RemoveField(
            model_name='word',
            name='lesson',
        ),
        migrations.AlterField(
            model_name='word',
            name='span',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='MissedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_missed', models.IntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missed_words', to='backendDB.lesson')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missed_words', to='backendDB.word')),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons_completed', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendDB.course')),
                ('missed_cards', models.ManyToManyField(blank=True, related_name='missed_by_users', to='backendDB.card')),
                ('missed_words', models.ManyToManyField(blank=True, related_name='missed_by_users', to='backendDB.missedword')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLessonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_to_complete', models.DurationField()),
                ('accuracy', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendDB.course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendDB.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WordThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendDB.lesson')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendDB.word')),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='lesson',
            field=models.ManyToManyField(related_name='words', to='backendDB.lesson'),
        ),
    ]
