# Generated by Django 5.1.3 on 2024-12-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendDB', '0008_card_times_missed_word_asl_remove_word_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='asl',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='word',
            name='span',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
