# Generated by Django 5.1.3 on 2024-12-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendDB', '0009_alter_word_asl_alter_word_span'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_pictures/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='word',
            name='asl',
            field=models.FileField(blank=True, null=True, upload_to='asl_translations/'),
        ),
    ]
