# Generated by Django 5.1.3 on 2024-12-21 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendDB', '0010_profilepicture_alter_word_asl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourse',
            old_name='course',
            new_name='courseID',
        ),
        migrations.RenameField(
            model_name='usercourse',
            old_name='user',
            new_name='userID',
        ),
    ]
