# Generated by Django 5.1.3 on 2024-12-21 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendDB', '0011_rename_course_usercourse_courseid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='courses',
        ),
    ]
