# Generated by Django 5.1.3 on 2024-12-21 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendDB', '0012_remove_user_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourse',
            old_name='courseID',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='usercourse',
            old_name='userID',
            new_name='user',
        ),
    ]
