# Generated by Django 5.1.3 on 2024-12-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendDB', '0013_rename_courseid_usercourse_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missedword',
            name='times_missed',
            field=models.IntegerField(default=1),
        ),
    ]
