# Generated by Django 5.1.3 on 2024-12-24 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendDB', '0014_alter_missedword_times_missed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pfp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='backendDB.profilepicture'),
        ),
    ]
