# Generated by Django 5.1.3 on 2024-12-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendDB', '0015_user_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisite',
            field=models.ManyToManyField(related_name='course', to='backendDB.course'),
        ),
    ]
