# Generated by Django 5.1.3 on 2024-12-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendDB', '0017_alter_course_prerequisite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='prerequisite',
            new_name='prerequisites',
        ),
    ]
